document.write('<script src="/lib/cmn_js/default.js"></script>');
document.write('<script src="/lib/cmn_js/innerlink.js"></script>');
document.write('<script src="/lib/cmn_js/jquery.js"></script>');
document.write('<script src="/lib/cmn_js/jquery.autoHeight.js"></script>');
document.write('<script src="/lib/cmn_js/jquery.opacity-rollover.js"></script>');
document.write('<script src="/lib/cmn_js/scrolltop/jquery_scrolltop.js"></script>');
document.write('<script src="/lib/cmn_js/fancybox/jquery.easing-1.3.pack.js"></script>');
document.write('<script src="/lib/cmn_js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>');
document.write('<link rel="stylesheet" href="/lib/cmn_js/fancybox/jquery.fancybox-1.3.4.css" media="all" />');
document.write('<script src="/lib/cmn_js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>');
document.write('<link rel="stylesheet" href="/lib/cmn_js/bxslider/jquery.bxslider.css" media="all">');
document.write('<script src="/lib/cmn_js/bxslider/jquery.bxslider.js"></script>');
document.write('<script src="/lib/cmn_js/jquery.parts.js"></script>');
document.write('<script src="/lib/cmn_js/viewport.js"></script>');
document.write('<script src="/lib/cmn_js/googleanalytics.js"></script>');